# HTTP Server (Tomcat) Port
server: 
  port: 2222

# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
error:
  whitelabel:
    enabled: false
spring:
   application:
     name: point_of_sale_auth
   datasource:
     driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
     url: jdbc:sqlserver://pointofsale.database.windows.net:1433;database=point_of_sale_auth;user=ramkishor05@pointofsale;password=Ram@9450;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
     username: ramkishor05
     password: Ram@9450
     show-sql: true
   jpa: 
     hibernate: 
       dialect: org.hibernate.dialect.MySQLDialect
       ddl-auto: update
       naming: 
         physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Discovery Server Access
eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:1111/eureka/
security:
    oauth2:
       resource:
         token-info-uri: http://localhost:8080/oauth/check_token
       client:        
         client-id: client
         client-secret: password
