# HTTP Server (Tomcat) Port
server: 
  port: 2222

# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
error:
  whitelabel:
    enabled: false
spring:
   application:
     name: point_of_sale_auth
   datasource:
     driverClassName: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://localhost:3306/point_of_sale_auth
     username: root
     password: root
     show-sql: true
   jpa: 
     hibernate: 
       dialect: org.hibernate.dialect.MySQLDialect
       ddl-auto: update
       naming: 
         physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Discovery Server Access
eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:1111/eureka/
security:
    oauth2:
       resource:
         token-info-uri: http://localhost:8080/oauth/check_token
       client:        
         client-id: client
         client-secret: password
